[package]
name = "Cody"
version = "0.1.0"
edition = "2024"

[lib]
name = "cody"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(rust_analyzer)'] }

[dependencies]
once_cell = "1.21.3"
