[package]
name = "engine"
version = "0.1.0"
edition = "2024"

[dependencies]
bitboard = { path = "../bitboard" }
criterion = "0.7.0"
once_cell = "1.21.3"
rand = "0.9.2"
rayon = "1.9"
time = "0.3"
humantime = "2.1"
rustc-hash = "2.1.1"

[[bench]]
name = "bench"
harness = false
